server:
    port: ${PORT:8850}

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ProyectoFabLab-Ciclo-VI/ProyectFalbLab-Configuration.git
